name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose

  fmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt --verbose --check

  doc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate docs
      run: cargo doc --no-deps
    - name: Archive generated docs
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: target/doc/

  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run clippy check
      run: cargo clippy --all-features --no-deps -- -D warnings

  miri:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        run: cargo miri test
