name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo build --verbose --features nrf52840

  doc:

    runs-on: ubuntu-latest

    env:
      RUSTDOCFLAGS: -D warnings

    steps:
    - uses: actions/checkout@v3
    - name: Generate docs
      run: cargo doc --no-deps --features nrf52840
    - name: Archive generated docs
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: target/doc/

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose --features mocked_platform

  fmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt --verbose --check

  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run clippy check
      run: cargo clippy --features mocked_platform --no-deps -- -D warnings

  miri:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        run: cargo miri test --features mocked_platform
